const lessonActionTypes = {
    LESSON_CREATE_START: 'LESSON_CREATE_START',
    LESSON_CREATE_SUCCESS: 'LESSON_CREATE_SUCCESS',
    LESSON_CREATE_FAILURE: 'LESSON_CREATE_FAILURE',
}

export default lessonActionTypes;