# Generated by Django 3.0.5 on 2020-04-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_organizer',
            new_name='is_admin',
        ),
    ]
